services:
  - type: web
    name: shl-assessment-recommender
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
